### ISSUE TITLE
Pay attention to the license

### ISSUE THREAD

**Issue by vdelachaux** [ArminDeeg/4D-WrirePro-Interface---WP-Toolbar#1]
Hi Armin,

Be careful, according to the license (which you distribute with your code), you must rename the component:

> • the Modified Software must be renamed to exclude any reference to 4D. For example, it is expressly prohibited to distribute a Modified Software named “4D SVG”; Licensee shall rename the Modified Software such as “Name of the Licensee SVG”. Consequently, Licensee is expressly forbidden to use 4D’s product name in general to promote his modified work.

**Comment by ArminDeeg** [comment]
Hi Vincent,

I offered my modified version since 4D v17 inside the 4D Forum. 
If I change the name of the project structure, it gets more complicated for other developer to use it.

My repo was added to the 4D awesome list on monday.
